artifactory_version: "7.125.7"
artifactory_repo_url: "https://releases.jfrog.io/artifactory/artifactory-pro-debs"
artifactory_gpg_key: "https://releases.jfrog.io/artifactory/api/v2/repositories/artifactory-pro-debs/keyPairs/primary/public"